### ISSUE TITLE
Loading issue on Safari

### ISSUE THREAD

**Issue by milosmns** [abdonrd/gdg-logo#3]
I tested this with Safari Version 9.1.2 (11601.7.7), on Mac OS X Version 10.11.6 (15G31).
The page won't load at all, I'm just getting a blank page.

**Comment by abdonrd** [comment]
I have the same OS X and Safari versions, and it works for me. 😕 

<img width="746" alt="screen shot 2016-08-31 at 16 10 14" src="https://cloud.githubusercontent.com/assets/1007051/18132054/7045696c-6f95-11e6-8745-323d4cd170d3.png">

**Comment by abdonrd** [comment]
Please, reopen if you issue persists.
